"""empty message

Revision ID: 0d3208e18b20
Revises: 
Create Date: 2019-04-29 15:20:05.864754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3208e18b20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provinces', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('provinces', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provinces', 'longitude')
    op.drop_column('provinces', 'latitude')
    # ### end Alembic commands ###
