"""empty message

Revision ID: 6d89cddda151
Revises: 
Create Date: 2019-06-09 20:12:16.375352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d89cddda151'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('bucket', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User', 'Cell', ['cell_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('Post', 'bucket')
    # ### end Alembic commands ###
