"""empty message

Revision ID: 8de81726ad8b
Revises: a4135de7b1dd
Create Date: 2019-04-30 15:39:29.688516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de81726ad8b'
down_revision = 'a4135de7b1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_images_post_id'), 'images', ['post_id'], unique=False)
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_index(op.f('ix_images_post_id'), table_name='images')
    # ### end Alembic commands ###
