"""empty message

Revision ID: 91322c9719a7
Revises: 
Create Date: 2019-05-09 20:27:28.917716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91322c9719a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_views_timestamp'), 'views', ['timestamp'], unique=False)
    op.create_index(op.f('ix_views_user_id'), 'views', ['user_id'], unique=False)
    op.create_index(op.f('ix_views_viewer_id'), 'views', ['viewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_views_viewer_id'), table_name='views')
    op.drop_index(op.f('ix_views_user_id'), table_name='views')
    op.drop_index(op.f('ix_views_timestamp'), table_name='views')
    op.drop_table('views')
    # ### end Alembic commands ###
