"""empty message

Revision ID: 98000999aed6
Revises: 0d3208e18b20
Create Date: 2019-04-29 15:44:15.618508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98000999aed6'
down_revision = '0d3208e18b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    # ### end Alembic commands ###
